#install httpd on linux server by sing ansible.
--- # Target playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Install httpd on linux
      action: yum name=httpd state=present
