#install httpd on linux server by sing ansible.
--- # Target playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: Install httpd on linux
      action: yum name=httpd state=present
#-------------------------------------------------------------------------------------------#
#Download tree packages by using variable.
--- # My variable playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  vars:
    packagename: tree
  tasks:
    - name: Install HTTPD on linux
      action: yum name='{{packagename}}' state=present
#-------------------------------------------------------------------------------------------#
#Download httpd package and start the service
--- # My handlers playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: Install HTTPD on linux
      action: yum name=httpd state=installed
      notify: restart httpd

  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted



